CREATE TABLESPACE GAUDETTE
DATAFILE 'C:\app\ouser\oradata\orcl\pdbkarp\GAUDETTE.dbf'
SIZE 50m
AUTOEXTEND ON NEXT 10m
MAXSIZE 500m
EXTENT MANAGEMENT LOCAL;

CREATE ROLE BIGDADDY;
GRANT ALL PRIVILEGES TO BIGDADDY;

SELECT PRIVILEGE FROM DBA_SYS_PRIVS WHERE GRANTEE='SYS'
MINUS
SELECT PRIVILEGE FROM DBA_SYS_PRIVS WHERE GRANTEE='BIGDADDY';

SELECT * FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT';

CREATE PROFILE ADMIN_PROFILE LIMIT
SESSIONS_PER_USER 2
CPU_PER_SESSION unlimited
CPU_PER_CALL unlimited
LOGICAL_READS_PER_SESSION unlimited
LOGICAL_READS_PER_CALL unlimited
IDLE_TIME unlimited  /* на время разработки */
CONNECT_TIME unlimited
FAILED_LOGIN_ATTEMPTS 2
PASSWORD_LIFE_TIME 30
PASSWORD_LOCK_TIME 1;

CREATE USER KARP IDENTIFIED BY Bst7825537
DEFAULT TABLESPACE GAUDETTE QUOTA UNLIMITED ON GAUDETTE
TEMPORARY TABLESPACE TEMP
PROFILE ADMIN_PROFILE
ACCOUNT UNLOCK;

GRANT BIGDADDY TO KARP;
GRANT SYSDBA TO KARP;
commit;
