CREATE SEQUENCE KARP.ÏÎ_טה
INCREMENT BY 1 START WITH 1
MAXVALUE 380 MINVALUE 1 
NOCYCLE NOCACHE;

CREATE SEQUENCE KARP.ÒÏ_טה
INCREMENT BY 1 START WITH 1000
NOMAXVALUE MINVALUE 1000
NOCYCLE NOCACHE;

CREATE SEQUENCE KARP.ÄÐ_טה
INCREMENT BY 1 START WITH 1
NOMAXVALUE MINVALUE 1 
NOCYCLE NOCACHE;

CREATE SEQUENCE KARP.ÇÑ_טה
INCREMENT BY 1 START WITH 1
NOMAXVALUE MINVALUE 1 
NOCYCLE NOCACHE;

